language: node_js
node_js:
  - "10.16.0"
cache:
  directories:
    - "node_modules"
script:
  - "npm run test:coverage:report"
deploy:
  provider: npm
  email: samuca_rs96@hotmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
branches:
  only:
    - master
