language: node_js
node_js:
  - "10.16.0"
before_install:
  - npm i -g makeshift && makeshift -s @samucars -r https://registry.npmjs.org
cache:
  directories:
    - "node_modules"
script:
  - "npm run test:coverage:report"
deploy:
  provider: npm
  email: samuca_rs96@hotmail.com
  api_key: $NPM_TOKEN
  on:
    repo: samucars/basketball-reference-js
    tags: true
